version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: OPENAI_API_KEY

  kg_rag:
    build:
      context: ../KG_RAG
      dockerfile: Dockerfile.flask
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=api.py